### ISSUE TITLE
CLI instructions feedback

### ISSUE THREAD

**Issue by cankisagun** [baedrik/SCRT-sealed-bid-auction#3]
It would be helpful to do the following for the CLI errors / user commands

Bob's bidding in an auction
- Insufficient funds (Low Priority):
![image](https://user-images.githubusercontent.com/15679491/102271587-98ffbc00-3eed-11eb-917c-7582987b35f9.png)
We can prompt you have 0 balance and the minimum bid amount is 0.115

**Comment by baedrik** [comment]
@cankisagun In that particular case, the error is coming from the sETH contract, because you are trying to send more than you have.  If on the other hand, you had enough of a balance for the sETH to do the Send, but the amount was less than the minimum, it would respond with a nicely formatted auction error message saying your bid did not meet the minimum.  Unfortunately I can't ever know every error message every SNIP20 token might respond with on a failed Send, so I was just opting to forward the error response the SNIP20 sent.  For this case I could do a search for the "insufficient funds" string and pretty up that one case, but any SNIP20 that doesn't use that wording would still slip through the prettying process

**Comment by cankisagun** [comment]
I don't think this is that important, we can deal with this error on the UI
